import unittest
from exercise import brute_force_greedy_set_cover, parse_input


class TestBeerFavourites(unittest.TestCase):
    def test_min_moves(self):
        employers, sorts = parse_input("6 3","YNN YNY YNY NYY NYY NYN")
        result = brute_force_greedy_set_cover(employers, sorts, 5)
        self.assertEqual(result, 2)

    def test_min_moves1(self):
        employers, sorts = parse_input("20 20", "NNYYNNNNNYNNYNYYYNNY NNNYNNNNNNNNNYNNNNYN YNYNYYYYNYYNNNNNNNNN NYYNNNNNNNNNNNNNYNNN NNNYNNNNNNNNNYNNNNYN YNYNNYNNYNNNYNNYNNNN NNNNNYNNNNNNNNNNNNNY NNYNNYYNNNYNYYNYYNNY NYNYNNNYNNNYNNNYYNNN NNYNNNYNYYYNNNYNNYNN YNNNNYNNYNNNNYYYYNNN NYNYYNNNYYNYNNYNYYNY YNNNYNNNYYYYNNNYNNNN NNNNYYNNNYYNNNNYNNYN NNYNNNNYYNYNNNNYYNNN YNYNNNNNNNNNNYYNNNNN NNNYNNYNNNNYNYYNNYNN NYYYYNYYYYNNNNNNYNNN NNYYNNNYNNYNYYNNNYNN NNNYYNYNNYYYNNYYNYNY")
        result = brute_force_greedy_set_cover(employers, sorts, 5)
        self.assertEqual(result, 4)

    def test_min_moves2(self):
        employers, sorts = parse_input("20 20", "NNYYNNNNNYNNYNYYYNNY NNNYNNNNNNNNNYNNNNYN YNYNYYYYNYYNNNNNNNNN NYYNNNNNNNNNNNNNYNNN NNNYNNNNNNNNNYNNNNYN YNYNNYNNYNNNYNNYNNNN NNNNNYNNNNNNNNNNNNNY NNYNNYYNNNYNYYNYYNNY NYNYNNNYNNNYNNNYYNNN NNYNNNYNYYYNNNYNNYNN YNNNNYNNYNNNNYYYYNNN NYNYYNNNYYNYNNYNYYNY YNNNYNNNYYYYNNNYNNNN NNNNYYNNNYYNNNNYNNYN NNYNNNNYYNYNNNNYYNNN YNYNNNNNNNNNNYYNNNNN NNNYNNYNNNNYNYYNNYNN NYYYYNYYYYNNNNNNYNNN NNYYNNNYNNYNYYNNNYNN NNNYYNYNNYYYNNYYNYNY")
        result = brute_force_greedy_set_cover(employers, sorts, 5)
        self.assertEqual(result, 4)


if __name__ == '__main__':
    unittest.main()